spring:
  mail:
    host: diracetechnology-com.mail.protection.outlook.com
    username: myomyintaung@diracetechnology.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

app:
  mail:
    templatePath: template/EmailTemplate.txt
    recipients:
      - htoolaekyaw@diracetechnology.com



